name: Update data

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-version: .tool-versions
          cache: 'npm'
      - run: npm install
      - name: Generate up-to-date airline data
        env:
          DUFFEL_ACCESS_TOKEN: ${{ secrets.DUFFEL_ACCESS_TOKEN }}
        run: npm run generate-airlines
      - name: Generate up-to-date aircraft data
        env:
          DUFFEL_ACCESS_TOKEN: ${{ secrets.DUFFEL_ACCESS_TOKEN }}
        run: npm run generate-aircraft
      - name: Generate up-to-date airport data
        env:
          DUFFEL_ACCESS_TOKEN: ${{ secrets.DUFFEL_ACCESS_TOKEN }}
        run: npm run generate-airports
      - uses: stefanzweifel/git-auto-commit-action@v6
        name: Commit and push any updates to data
        id: commit
        with:
          commit_message: Add latest airline, aircraft and airport data from Duffel
          file_pattern: 'data/*.json'
      - name: Trigger deploy if data changed
        uses: actions/github-script@v8
        if: steps.commit.outputs.changes_detected == 'true'
        with:
          script: |
            await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main_iata-code-decoder-api-docker.yml',
              ref: 'main'
            });
