name: Update airline data

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: 'npm'
      - run: npm install
      - name: Generate up-to-date airline data
        env:
          DUFFEL_ACCESS_TOKEN: ${{ secrets.DUFFEL_ACCESS_TOKEN }}
        run: npm run generate-airlines
      - uses: stefanzweifel/git-auto-commit-action@v5
        name: Commit and push any updates to airline data
        id: commit
        with:
          commit_message: Add latest airline data from Duffel
          file_pattern: data/airlines.json
      - name: Trigger deploy if airline data changed
        uses: actions/github-script@v7
        if: steps.commit.outputs.changes_detected == 'true'
        with:
          script: |
            await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main_iata-code-decoder-api-docker.yml',
              ref: 'main'
            });
